version: 2.1
orbs:
  go: {}
  orb-tools: circleci/orb-tools@12.0

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  int-test-goreleaser-install:
    executor:
      name: go/default
      tag: "1.23"
    steps:
      - go/install-goreleaser
  int-test-goreleaser-release:
    executor:
      name: go/default
      tag: "1.23"
    steps:
      - go/install-goreleaser
      - go/goreleaser-release:
          github-token: TEST_GH_TOKEN
          validate-yaml: true
          publish-release: false
          project-path: ~/project/tests
  int-test-cimg-go:
    executor:
      name: go/default
      tag: "1.23"
    steps:
      - run:
          name: "Check out sample project."
          command: git clone https://github.com/CircleCI-Public/circleci-demo-go.git ~/project
      - go/with-cache:
          key: "integration"
          mod: true
          golangci-lint: true
          steps:
            - go/mod-download
            - run: go version && go build ./...
  int-test-cimg-base:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Check out sample project."
          command: git clone https://github.com/CircleCI-Public/circleci-demo-go.git ~/project
      - go/install
      - go/with-cache:
          key: "integration"
          mod: true
          golangci-lint: true
          steps:
            - go/mod-download
            - run: go version && go build ./...
  int-test-cimg-python:
    docker:
      - image: cimg/python:3.11
    steps:
      - go/install:
          version: 1.17.2
      - run:
          name: "Check if the correct python version is accessible & installed"
          command: python --version | grep -q "^Python 3.11"
  int-test-macos-executor:
    macos:
      xcode: "14.1.0"
    steps:
      - run:
          name: "Check out sample project."
          command: git clone https://github.com/CircleCI-Public/circleci-demo-go.git ~/project
      - go/install
      - go/with-cache:
          key: "integration"
          mod: true
          golangci-lint: true
          steps:
            - go/mod-download
            - run: go version && go build ./...
  int-test-vm-linux:
    machine:
      image: ubuntu-2004:current
    steps:
      - run:
          name: "Check out sample project."
          command: git clone https://github.com/CircleCI-Public/circleci-demo-go.git ~/project
      - go/install:
          version: 1.16.4
      - go/with-cache:
          key: "integration"
          mod: true
          golangci-lint: true
          steps:
            - go/mod-download
            - run: go version && go build ./...
  int-test-vm-arm64:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - run:
          name: "Check out sample project."
          command: git clone https://github.com/CircleCI-Public/circleci-demo-go.git ~/project
      - go/install:
          version: 1.16.4
      - go/with-cache:
          key: "integration"
          mod: true
          golangci-lint: true
          steps:
            - go/mod-download
            - run: go version && go build ./...
  # test to make sure the dirty cache issue doesn't crop back up
  int-test-dirty-cache:
    machine:
      image: ubuntu-2004:current
    steps:
      - run:
          name: "Check out sample project."
          command: git clone https://github.com/CircleCI-Public/circleci-demo-go.git ~/project
      - go/install:
          version: 1.15.1
      - go/load-mod-cache:
          key: "integration"
      - go/mod-download
      - run: go version && go build ./...
      - go/save-mod-cache:
          key: "integration"
      - go/install:
          version: 1.16.4
      - run: go version && go build ./...
  go-test-default:
    docker:
      - image: cimg/go:1.23.3
    steps:
      - checkout
      - go/test:
          project-path: tests
  go-test-default-1-19:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - go/test:
          project-path: tests
  int-test-gotestsum-1-test:
    docker:
      - image: cimg/go:1.23.3
    steps:
      - checkout
      - go/gotestsum:
          project-path: tests
          packages: circleci.com/go-orb/numbers
      - store_test_results:
          path: /home/circleci/project/tests
  int-test-gotestsum-2-test:
    docker:
      - image: cimg/go:1.23.3
    steps:
      - checkout
      - go/gotestsum:
          project-path: tests
          packages: circleci.com/go-orb/numbers circleci.com/go-orb/words
      - store_test_results:
          path: /home/circleci/project/tests
  int-test-gotestsum-all-test:
    docker:
      - image: cimg/go:1.23.3
    steps:
      - checkout
      - go/gotestsum:
          project-path: tests
      - store_test_results:
          path: /home/circleci/project/tests
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - int-test-goreleaser-install:
          filters: *filters
      - int-test-goreleaser-release:
          pre-steps:
            - checkout
            - run:
                name: Change to test directory
                command: cd ~/project/tests
          filters: *filters
      - int-test-cimg-go:
          filters: *filters
      - int-test-cimg-base:
          filters: *filters
      - int-test-cimg-python:
          filters: *filters
      - int-test-macos-executor:
          filters: *filters
      - int-test-vm-linux:
          filters: *filters
      - int-test-dirty-cache:
          filters: *filters
      - int-test-vm-arm64:
          filters: *filters
      - go-test-default:
          filters: *filters
      - go-test-default-1-19:
          filters: *filters
      - int-test-gotestsum-1-test:
          filters: *filters
      - int-test-gotestsum-2-test:
          filters: *filters
      - int-test-gotestsum-all-test:
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: circleci/go
          vcs_type: << pipeline.project.type >>
          pub_type: production
          github_token: GHI_TOKEN
          requires:
            - orb-tools/pack
            - int-test-cimg-go
            - int-test-cimg-base
            - int-test-cimg-python
            - int-test-macos-executor
            - int-test-vm-linux
            - int-test-dirty-cache
            - int-test-vm-arm64
            - int-test-goreleaser-install
            - int-test-goreleaser-release
          context: orb-publisher
          filters: *release-filters
