description: "The official CircleCI Go Docker image."
parameters:
  tag:
    description: "The `circleci/golang` Docker image version tag."
    type: string
    default: "latest"
docker:
  - image: circleci/golang:<< parameters.tag >>
